# Generated by Django 2.1.2 on 2018-10-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('nombreMascota', models.CharField(max_length=200)),
                ('raza_predominante', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='postulante',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
