# Generated by Django 2.1.2 on 2018-10-29 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181028_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='fechaNacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='fechaPostulacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
