# Generated by Django 2.1.2 on 2018-10-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181029_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.TextField(choices=[('disponible', 'Disponible'), ('adoptado', 'Adoptado'), ('rescatado', 'Rescatado')]),
        ),
    ]
